name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit:
    name: Unit
    env:
      NODE_OPTIONS: --experimental-vm-modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  functional:
    name: Functional
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Authorize SSH Connections
      uses: ./
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-1'
        aws-security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
        protocol: 'tcp'
        port: ${{ secrets.SSH_PORT }}
    - name: Runs a command inside the instance
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "It works!"
